/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppMenu: typeof import('./components/AppMenu.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    Equipment: typeof import('./components/equipment.vue')['default']
    EquipmentForm: typeof import('./components/EquipmentForm.vue')['default']
    EquipmentsList: typeof import('./components/EquipmentsList.vue')['default']
    FormLogin: typeof import('./components/FormLogin.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUpForm: typeof import('./components/SignUpForm.vue')['default']
  }
}
