/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivitiesList: typeof import('./components/ActivitiesList.vue')['default']
    ActivityCard: typeof import('./components/ActivityCard.vue')['default']
    ActivityForm: typeof import('./components/ActivityForm.vue')['default']
    ActivityUpload: typeof import('./components/ActivityUpload.vue')['default']
    ActivityView: typeof import('./components/ActivityView.vue')['default']
    AppMenu: typeof import('./components/AppMenu.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    Equipment: typeof import('./components/equipment.vue')['default']
    EquipmentForm: typeof import('./components/EquipmentForm.vue')['default']
    EquipmentsList: typeof import('./components/EquipmentsList.vue')['default']
    FormLogin: typeof import('./components/FormLogin.vue')['default']
    Graph: typeof import('./components/Graph.vue')['default']
    GraphBar: typeof import('./components/Graph-bar.vue')['default']
    GraphLine: typeof import('./components/Graph-line.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    ProfileForm: typeof import('./components/ProfileForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUpForm: typeof import('./components/SignUpForm.vue')['default']
  }
}
