/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/activities': RouteRecordInfo<'/activities', '/activities', Record<never, never>, Record<never, never>>,
    '/activity/[id]': RouteRecordInfo<'/activity/[id]', '/activity/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/activity/[id]/edit': RouteRecordInfo<'/activity/[id]/edit', '/activity/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/activity/add': RouteRecordInfo<'/activity/add', '/activity/add', Record<never, never>, Record<never, never>>,
    '/equipment/add': RouteRecordInfo<'/equipment/add', '/equipment/add', Record<never, never>, Record<never, never>>,
    '/equipments': RouteRecordInfo<'/equipments', '/equipments', Record<never, never>, Record<never, never>>,
    '/health': RouteRecordInfo<'/health', '/health', Record<never, never>, Record<never, never>>,
    '/health/import': RouteRecordInfo<'/health/import', '/health/import', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/profile/edit': RouteRecordInfo<'/profile/edit', '/profile/edit', Record<never, never>, Record<never, never>>,
    '/profile/view': RouteRecordInfo<'/profile/view', '/profile/view', Record<never, never>, Record<never, never>>,
    '/signup': RouteRecordInfo<'/signup', '/signup', Record<never, never>, Record<never, never>>,
  }
}
